name: traxie
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  hive: ^2.2.3
  intl: ^0.20.2
  meta: ^1.16.0
  path_provider: ^2.1.5
  step_progress_indicator: ^1.0.2
  table_calendar: ^3.1.3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
